### ISSUE TITLE
TODO: v0.2

### ISSUE THREAD

**Issue by jinyoungbang** [whyphi/tracker#1]
### AWS
- [x] Setting up AWS Parameter Store on Lambda for env vars to be read on cloud https://github.com/whyphi/zap/pull/32

### Server
- [ ] ORM/Model Mapping Research for Validation and Maintainability Purposes
- [ ] Implement Authentication using Google's Outh `id_token`
- [x] Email Confirmation Send through AWS SES https://github.com/whyphi/zap/pull/24
- [x] Bug fix on update and delete listing on production https://github.com/whyphi/zap/pull/27

### Misc
- [x] Build Unit Testing Infra https://github.com/whyphi/zap/pull/17
- [x] Refactoring Codebase and routes by logic/feature https://github.com/whyphi/zap/pull/15

### Public
- [x] Confirmation Checkboxes https://github.com/whyphi/portal/pull/54
- [x] Only allow PDF resume submissions - Implement file validator https://github.com/whyphi/portal/pull/28
- [x] Implement Button Loader when form is being submitted through the server (loading state + disable button) https://github.com/whyphi/portal/pull/29
- [x] Refactor Forms to take in Events Attended Checkbox https://github.com/whyphi/portal/pull/34
- [x] Bugfix: File Upload Size over 6MB (for applications) https://github.com/whyphi/portal/pull/52

### Admin
- [x] Create Copy Link Button to copy listing button https://github.com/whyphi/portal/pull/25
- [x] Implement Edit, Delete Button/Dropdown on Listing Card https://github.com/whyphi/portal/pull/25
- [x] Implement View Analytics on Listing (Shows relevant data points) https://github.com/whyphi/portal/pull/32
- [x] Members Page https://github.com/whyphi/zap/pull/32
- [ ] Implement Alumni DB Page https://github.com/whyphi/portal/pull/27
- [ ] Implement Accountability Points Semester Data Display Page https://github.com/whyphi/portal/pull/35
- [x] Implement Accountability Points New Semester Create Page https://github.com/whyphi/portal/pull/35
- [x] Preview Public Listing (disable submission button and external API calls) https://github.com/whyphi/portal/pull/51
- [x] Card Link Bug + Redesign https://github.com/whyphi/portal/pull/39

### General
- [x] Metadata Setting https://github.com/whyphi/portal/pull/47

## Extra
- [x] Add PCT Members to Vault
