### ISSUE TITLE
TODO: v1.0

### ISSUE THREAD

**Issue by jinyoungbang** [whyphi/tracker#2]
### AWS
TBD

### Server
- [ ] Auto-sync user's token/id (from Google Auth) to MongoDB on register or login
- [ ] Create Member-related APIs (Update, fetch, etc)
- [ ] Create Pass/Wallet Feature for Personalized QR-Code Check-in
- [ ] Implement and improve descriptive AWS Monitoring logs for CloudWatch (for Observability purposes)
- [ ] Develop masking/encryption for sensitive user rush information
- [ ] Slack Announcements API

### Misc
TBD

### Public
- [ ] Login Page by Privilege
- [ ] Bugfix: Fix login issues where user cannot sign out when only logged into one google account

### Admin
- [ ] Create additional analytics page
- [ ] Integrate Slack Announcements to Announcements Feature
- [ ] Create Pass/Wallet Feature for Personalized QR-Code Check-in
- [ ] Create QR-Code Scanning Feature (Mobile App? Web converted into Mobile? Directly from laptop?)
- [ ] OPTIONAL: Brother Spotting Leaderboard

### General
- [ ] OPTIONAL: Develop Frontend Testing Infrastructure

## Extra
- [ ] Finalize Frontend Onboarding Guide
- [ ] Create Documentation on how to set up AWS resource permissions
- [ ] Create API Documentation for Zap API Routes

**Comment by jinyoungbang** [comment]
General Features to Develop over the Semester

- Syncing Slack Announcements with Whyphi
- Developing Sign-in Pass System
- Building Rushee Feedback System (Commenting, Rating)
- Adding Interview Results for Rushees on Whyphi to be viewed during Screening/Deliberations
