### ISSUE TITLE
TODO: rushee attendence

### ISSUE THREAD

**Issue by wderocco8** [whyphi/tracker#3]
# Goal: Fully integrate rushee attendance into `portal` events.

### Backend

- [x] add deadline to `event` objects
- [x] add `currentEventCategory` field to enable us to see which event is currently set (ties into next bullet)
- [x] add backend endpoint to fetch list of events (this should be done dynamically depending on what semester we are in)... NOTE: should ensure that the `code` is not fetched as well

### Frontend

- [x] image upload (with cropping enabled)... see [this library](https://www.npmjs.com/package/react-image-crop)
- [x] call backend endpoint ^ to get all potential events
    - [x] disable events past their deadlines
    - [x] when clicking on an event, route to `/events/rush/{event_id}`
- [x] add event-preview page before creating an event
- [ ] enable rushees to **track** their attendance (and see whether they have enough to interview)

### Pytest validation on...
- [ ] modify rush events
- [ ] update currentEventCategory

## Nice to have features:

- [ ] validate rushee location before allowing them to check-in
